### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by ramoncaldeira** [sleede/wupee#1]
Hello! I am getting ActionView::MissingTemplate error .-. 
Instead of searching on views/wupee/notifications/:notification_type.html.erb, rails is searching only on views/notifications_mailer

**Comment by nflorentin** [comment]
Hi ! 

this is the intented behaviour, rails search in views/mailer_name directory due to this configuration:
`Wupee.mailer = NotificationsMailer`.
I think inheritate from Wupee::NotificationsMailer make easier to customize the mailer.
But I'm open to better solutions if you have one.

To sum up:
- mails views are in `views/mailer_name` directory and are not partials. Example: `views/notifications_mailer/new_follower.html.erb`
- notification partials, to be rendered into html views, are in `views/wupee/notifications/`. Example: `views/wupee/notifications/_new_follower.html.erb`
- json views, to be used via the json API, are in `views/wupee/api/notifications/`. Example: `views/wupee/api/notifications/_new_follower.json.jbuilder`
